const {chromium}=require(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES+'/playwright');
const fs=require('fs'),assert=require('assert'),{spawn}=require('child_process'),os=require('os'),path=require('path');
(async()=>{const result={checks:[],errors:[],environment:'Chromium 133 headless; Forge 1.8.9 Launcher'};let browser;const server=spawn('python3',['launcher/app.py','--no-browser','--port','18789','--data',fs.mkdtempSync(path.join(os.tmpdir(),'ttro-qa-'))]);await new Promise((resolve,reject)=>{server.stdout.once('data',resolve);server.once('exit',()=>reject(Error('Launcher exited')));});const check=(name,value)=>{assert(value,name);result.checks.push({name,status:'PASS'});};
try{browser=await chromium.launch({executablePath:process.env.TTRO_CHROMIUM,headless:true,args:['--no-sandbox']});const p=await browser.newPage({viewport:{width:1280,height:900}});p.on('pageerror',e=>result.errors.push(e.message));
await p.goto('http://127.0.0.1:18789');await p.waitForSelector('h1');check('Ttro Client title',await p.title()==='Ttro Client');check('Forge 1.8.9 PLAY',(await p.locator('main').innerText()).includes('1.8.9'));await p.screenshot({path:'research/ui-play.png',fullPage:true});
await p.locator('#search-open').focus();await p.keyboard.press('Control+k');await p.locator('#command-query').fill('スクロール');await p.keyboard.press('Enter');await p.waitForSelector('#inventory-rightDrag');check('purpose search reaches inventory',p.url().endsWith('#tune/inventory'));check('six Inventory Controls',await p.locator('[data-param^="inventory."]').count()===6);await p.screenshot({path:'research/ui-inventory.png',fullPage:true});
await p.locator('#inventory-leftCollect').uncheck();await p.locator('#inventory-wheel').uncheck();await p.waitForTimeout(500);await p.reload();await p.waitForSelector('#inventory-wheel');check('rapid independent edits retained',!(await p.locator('#inventory-leftCollect').isChecked())&&!(await p.locator('#inventory-wheel').isChecked()));await p.locator('#inventory-leftCollect').check();await p.locator('#inventory-wheel').check();await p.waitForTimeout(450);
await p.keyboard.press('Control+k');await p.locator('#command-query').fill('no-such-feature');check('empty command results',await p.locator('#command-results').innerText().then(t=>t.includes('ありません')));await p.keyboard.press('Escape');check('dialog Escape closes',!await p.locator('#palette').evaluate(d=>d.open));
await p.goto('http://127.0.0.1:18789/#style/reach');await p.waitForSelector('[data-enable="reach"]');check('candidate reach disabled',await p.locator('[data-enable="reach"]').isDisabled());
await p.goto('http://127.0.0.1:18789/#style/fullbright');await p.waitForSelector('[data-enable="fullbright"]');check('external provider absent cannot enable',await p.locator('[data-enable="fullbright"]').isDisabled());check('external provider absence explained',await p.locator('#context').innerText().then(t=>t.includes('未導入')));
await p.goto('http://127.0.0.1:18789/#tune/mousedelay');await p.waitForSelector('[data-foundation="mousedelay"]');check('foundation is install status not a toggle',await p.locator('[data-enable="mousedelay"]').count()===0&&await p.locator('[data-foundation="mousedelay"]').innerText()==='未導入');check('foundation badge does not wrap',await p.locator('[data-foundation="mousedelay"]').evaluate(e=>getComputedStyle(e).whiteSpace==='nowrap'&&e.scrollWidth<=e.clientWidth));check('foundation semantics explained',await p.locator('#context').innerText().then(t=>t.includes('常設の入力修正')));
await p.goto('http://127.0.0.1:18789/#tune/inputfix');await p.waitForSelector('#inputfix-layout');await p.locator('#inputfix-layout').selectOption('FR AZERTY');await p.waitForTimeout(350);await p.reload();await p.waitForSelector('#inputfix-layout');check('foundation safety does not claim session blocking',await p.locator('#context').innerText().then(t=>t.includes('許可を保証しません')));check('keyboard layout persists',await p.locator('#inputfix-layout').inputValue()==='FR AZERTY');await p.screenshot({path:'research/ui-foundation.png',fullPage:true});
await p.goto('http://127.0.0.1:18789/#style/headfx');await p.waitForSelector('#headfx-preset');await p.locator('#headfx-preset').selectOption('Glow');await p.waitForTimeout(400);await p.reload();await p.waitForSelector('#headfx-preset');check('HeadFX persists',await p.locator('#headfx-preset').inputValue()==='Glow');await p.screenshot({path:'research/ui-style.png',fullPage:true});
await p.goto('http://127.0.0.1:18789/#style/fps');await p.waitForSelector('[data-hud="layout"]',{state:'attached'});await p.locator('#context details summary').click();await p.locator('[data-hud="layout"]').selectOption('individual');await p.locator('[data-hud-element="fps"][data-hud="x"]').fill('220');await p.locator('[data-hud-element="fps"][data-hud="x"]').press('Tab');await p.waitForTimeout(450);await p.reload();await p.waitForSelector('[data-hud="layout"]',{state:'attached'});check('individual HUD placement persists',await p.locator('[data-hud-element="fps"][data-hud="x"]').inputValue()==='220');await p.locator('#context details summary').click();await p.locator('[data-hud="layout"]').selectOption('clusters');await p.waitForTimeout(300);
for(const width of [1280,768,390,320]){await p.setViewportSize({width,height:900});check('horizontal reflow '+width,await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));if(width===390)await p.screenshot({path:'research/ui-mobile.png',fullPage:true});}
await p.setViewportSize({width:640,height:450});check('200 percent equivalent reflow',await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await p.emulateMedia({reducedMotion:'reduce'});check('reduced motion',await p.evaluate(()=>matchMedia('(prefers-reduced-motion:reduce)').matches));
await p.goto('http://127.0.0.1:18789/#library/resourcepack');await p.waitForSelector('#browse-query');check('library empty state',await p.locator('#content-list').innerText().then(t=>t.includes('追加されていません')));await p.locator('#content-file').setInputFiles('tests/fixtures/pack-a.zip');await p.waitForSelector('[data-preview="pack-a.zip"]');await p.locator('#content-file').setInputFiles('tests/fixtures/pack-b.zip');await p.waitForSelector('[data-preview="pack-b.zip"]');check('resource packs imported in UI',await p.locator('[data-preview]').count()===2);await p.locator('[data-content="pack-a.zip"][data-op="disable"]').click();await p.waitForSelector('[data-content="pack-a.zip"][data-op="enable"]');check('pack disable and enable available',true);await p.locator('[data-content="pack-a.zip"][data-op="enable"]').click();await p.waitForSelector('[data-content="pack-a.zip"][data-op="disable"]');await p.locator('[data-content="pack-b.zip"][data-op="up"]').click();await p.waitForTimeout(200);await p.locator('[data-preview="pack-a.zip"]').click();await p.waitForSelector('#modal[open]');check('pack preview empty images explained',await p.locator('#modal-body').innerText().then(t=>t.includes('画像')));await p.keyboard.press('Escape');await p.route('**/api/search?**',r=>r.fulfill({status:400,contentType:'application/json',body:JSON.stringify({error:'QA: network unavailable'})}));await p.locator('#browse-query').fill('PvP');await p.locator('#browse-form button').click();await p.waitForSelector('#browse-results .error-box');check('search error retry',await p.locator('#browse-results').innerText().then(t=>t.includes('再試行')));
await p.goto('http://127.0.0.1:18789/prototypes.html');for(const direction of ['ribbon','dock','flow']){await p.locator('[data-variant="'+direction+'"]').click();await p.locator('[data-view="tune"]').click();await p.locator('#study-crosshair').click();check('interactive direction '+direction,await p.locator('#study-reticle').count()===1);}
check('no JS runtime errors',result.errors.length===0);result.status='PASS';
}catch(e){result.status='FAIL';result.error=e.stack;throw e;}finally{fs.writeFileSync('research/ui-result.json',JSON.stringify(result,null,2));if(browser)await browser.close();server.kill();}})();
