const {chromium}=require(process.env.TTRO_USE_LOCAL_PLAYWRIGHT?'playwright':process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES+'/playwright');
const assert=require('assert'),{spawn}=require('child_process');
(async()=>{let browser;const server=spawn('python3',['-u','-m','http.server','18790','--bind','127.0.0.1','--directory','website']);await new Promise((r,j)=>{server.stdout.once('data',r);server.stderr.once('data',r);server.once('exit',()=>j(Error('Web server exited')));});let checks=0;function check(v,n){assert(v,n);checks++;console.log('PASS '+n)}
try{browser=await chromium.launch({executablePath:process.env.TTRO_CHROMIUM,headless:true,args:['--no-sandbox']});const page=await browser.newPage();let errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.route('https://api.github.com/**',r=>r.fulfill({json:[]}));await page.goto('http://127.0.0.1:18790');await page.getByText('Download for Windows · 準備中',{exact:true}).waitFor();check(await page.locator('#download').getAttribute('href')===null,'no invented download for empty releases');
for(const width of [1920,1280,768,390,320]){await page.setViewportSize({width,height:850});check(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'responsive width '+width)}
await page.keyboard.press('Tab');check(await page.locator('.skip').evaluate(e=>e===document.activeElement),'keyboard skip link');
await page.unroute('https://api.github.com/**');await page.route('https://api.github.com/**',r=>r.fulfill({json:[{draft:false,prerelease:true,tag_name:'v0.3.0-alpha.1',assets:[{name:'TtroClient-Setup.exe',browser_download_url:'https://github.com/totoro0419/TtroClient/releases/download/v0.3.0-alpha.1/TtroClient-Setup.exe'},{name:'checksums.txt',browser_download_url:'https://github.com/totoro0419/TtroClient/releases/download/v0.3.0-alpha.1/checksums.txt'}]}]}));await page.reload();await page.waitForSelector('#download[href]');check((await page.locator('#release-state').innerText()).includes('Public Alpha'),'alpha status follows actual release metadata');check((await page.locator('#checksums').getAttribute('href')).endsWith('/checksums.txt'),'checksums same release');
await page.unroute('https://api.github.com/**');
await page.route('https://api.github.com/**',r=>r.fulfill({json:[{draft:false,prerelease:false,tag_name:'v9.9.9',assets:[{name:'TtroClient-Setup.exe',browser_download_url:'https://github.com/totoro0419/TtroClient/releases/download/v9.9.9/TtroClient-Setup.exe'},{name:'checksums.txt',browser_download_url:'https://github.com/totoro0419/TtroClient/releases/download/v9.9.9/checksums.txt'}]}]}));
await page.reload();await page.getByText('Download for Windows · 準備中',{exact:true}).waitFor();check(await page.locator('#download').getAttribute('href')===null,'stable release never substituted as alpha');
await page.unroute('https://api.github.com/**');await page.route('https://api.github.com/**',r=>r.fulfill({status:503,body:'unavailable'}));await page.reload();await page.getByText('Download for Windows · 確認できません',{exact:true}).waitFor();check(await page.locator('#download').getAttribute('href')===null,'network failure does not activate download');check(errors.length===0,'no browser script errors');console.log(checks+' checks passed.');
}finally{if(browser)await browser.close();server.kill();}})().catch(e=>{console.error(e);process.exitCode=1});
