package dev.ttro.qa;
import java.util.*;import java.io.*;import java.lang.reflect.*;import java.awt.Robot;import java.awt.event.InputEvent;import java.nio.file.*;
import com.google.gson.*;
import net.minecraft.client.*;import net.minecraft.client.gui.*;import net.minecraft.client.gui.inventory.*;import net.minecraft.client.renderer.*;import net.minecraft.client.settings.*;import net.minecraft.util.*;import net.minecraft.world.*;import net.minecraft.entity.player.*;import net.minecraft.item.*;import net.minecraft.init.*;import net.minecraft.inventory.*;import net.minecraft.scoreboard.*;
import net.minecraftforge.fml.common.*;import net.minecraftforge.fml.common.event.*;import net.minecraftforge.fml.common.eventhandler.*;import net.minecraftforge.fml.common.gameevent.*;
@Mod(modid="ttroqa",name="Ttro Client isolated QA",version="1",clientSideOnly=true,acceptedMinecraftVersions="[1.8.9]")
public final class Probe {
 int ticks,stage,elapsed,sub;boolean ttro;Robot robot;JsonObject result=new JsonObject();JsonArray checks=new JsonArray(),frames=new JsonArray();long last;boolean previousCrosshair;int inventoryKey;int benchmarkWindow,frameCount;final long[] frameNanos=new long[60000],frameHeap=new long[60000];final byte[] frameModes=new byte[60000];final short[] frameWindows=new short[60000];
 final String[] cases={"right-drag","left-collect","shift-drag","wheel-out","wheel-in","wheel-in-first","wheel-in-last","reverse-out","reverse-in"};
 @Mod.EventHandler public void init(FMLInitializationEvent e)throws Exception{ttro=Loader.isModLoaded("ttro189");robot=new Robot();result.addProperty("environment","Minecraft 1.8.9 / Forge 11.15.1.2318 / Java 8 / Xvfb / Mesa software / 960x540");result.addProperty("Ttro",ttro);result.add("checks",checks);result.add("frames",frames);FMLCommonHandler.instance().bus().register(this);}
 void check(String name,boolean pass){JsonObject c=new JsonObject();c.addProperty("name",name);c.addProperty("status",pass?"PASS":"FAIL");checks.add(c);save();}
 void save(){try{if(frameCount>0&&frames.size()!=frameCount){frames=new JsonArray();for(int i=0;i<frameCount;i++){JsonObject frame=new JsonObject();frame.addProperty("mode",frameModes[i]==0?"OFF":"ON");frame.addProperty("window",frameWindows[i]);frame.addProperty("ms",frameNanos[i]/1e6);frame.addProperty("heap",frameHeap[i]);frames.add(frame);}result.add("frames",frames);}Path d=Minecraft.getMinecraft().mcDataDir.toPath().resolve("qa-results");Files.createDirectories(d);Files.write(d.resolve("result.json"),new GsonBuilder().setPrettyPrinting().create().toJson(result).getBytes("UTF-8"));}catch(Exception ex){throw new RuntimeException(ex);}}
 /** Independent synchronous QA capture. Upstream screenshot optimizers can
  * return before their workers finish PNG writes; never accept partial evidence. */
 void shot(String name)throws Exception{Minecraft m=Minecraft.getMinecraft();File d=new File(m.mcDataDir,"qa-results/screenshots");d.mkdirs();net.minecraft.client.shader.Framebuffer f=m.getFramebuffer();int w=f.framebufferTextureWidth,h=f.framebufferTextureHeight;java.nio.IntBuffer pixels=org.lwjgl.BufferUtils.createIntBuffer(w*h);int texture=org.lwjgl.opengl.GL11.glGetInteger(org.lwjgl.opengl.GL11.GL_TEXTURE_BINDING_2D);
  org.lwjgl.opengl.GL11.glPixelStorei(org.lwjgl.opengl.GL11.GL_PACK_ALIGNMENT,1);GlStateManager.bindTexture(f.framebufferTexture);
  try{org.lwjgl.opengl.GL11.glGetTexImage(org.lwjgl.opengl.GL11.GL_TEXTURE_2D,0,org.lwjgl.opengl.GL12.GL_BGRA,org.lwjgl.opengl.GL12.GL_UNSIGNED_INT_8_8_8_8_REV,pixels);}finally{GlStateManager.bindTexture(texture);}
  int[] image=new int[m.displayWidth*m.displayHeight];for(int y=0;y<m.displayHeight;y++)for(int x=0;x<m.displayWidth;x++)image[y*m.displayWidth+x]=pixels.get((h-1-y)*w+x);
  java.awt.image.BufferedImage bitmap=new java.awt.image.BufferedImage(m.displayWidth,m.displayHeight,java.awt.image.BufferedImage.TYPE_INT_RGB);bitmap.setRGB(0,0,m.displayWidth,m.displayHeight,image,0,m.displayWidth);
  if(!javax.imageio.ImageIO.write(bitmap,"png",new File(d,name+".png")))throw new IOException("PNG encoder unavailable");
 }
 JsonObject data()throws Exception{return (JsonObject)Class.forName("dev.ttro.Config").getField("data").get(null);}
 void apply()throws Exception{Class.forName("dev.ttro.Core").getMethod("apply").invoke(null);}
 void module(String id,boolean on)throws Exception{if(ttro)data().getAsJsonObject("modules").getAsJsonObject(id).addProperty("enabled",on);}
 void offHud()throws Exception{Class<?> core=Class.forName("dev.ttro.Core"),config=Class.forName("dev.ttro.Config");JsonObject saved=new JsonParser().parse(data().toString()).getAsJsonObject();
  for(String id:new String[]{"fps","ping","cps","keystrokes","bps","coordinates","memory","armor","potions","items","clock","connection"})module(id,false);module("crosshair",true);apply();
  Field hud=core.getDeclaredField("hudRegistered"),crosshair=core.getDeclaredField("crosshairRegistered");hud.setAccessible(true);crosshair.setAccessible(true);check("Crosshair alone leaves HUD polling unregistered",!hud.getBoolean(null)&&crosshair.getBoolean(null));config.getField("data").set(null,saved);apply();
 }
 void patcherSettings()throws Exception{
  if(!Boolean.getBoolean("ttro.qa.patcher"))return;Class<?> p=Class.forName("club.sk1er.patcher.config.PatcherConfig");
  check("official Patcher and OneConfig loaded",Loader.isModLoaded("patcher")&&Loader.isModLoaded("oneconfig"));
  p.getField("screenshotManager").setBoolean(null,false); // QA captures use synchronous vanilla writer, not upstream asynchronous screenshot workers.
  module("fullbright",false);apply();check("Fullbright OFF overrides Patcher default",!p.getField("fullbright").getBoolean(null));
  module("fullbright",true);apply();check("Fullbright ON reaches Patcher",p.getField("fullbright").getBoolean(null));module("fullbright",false);apply();
  module("reducedfire",true);JsonObject fire=data().getAsJsonObject("modules").getAsJsonObject("reducedfire");fire.addProperty("height",.7);fire.addProperty("opacity",35);apply();
  check("Reduced Fire height and opacity reach Patcher",Math.abs(p.getField("fireOverlayHeight").getFloat(null)-.7f)<.001&&p.getField("fireOverlayOpacityI").getInt(null)==35&&Math.abs(p.getField("fireOverlayOpacity").getFloat(null)-.35f)<.001);
  module("reducedfire",false);apply();check("Reduced Fire OFF restores vanilla",p.getField("fireOverlayHeight").getFloat(null)==0&&p.getField("fireOverlayOpacityI").getInt(null)==100&&p.getField("fireOverlayOpacity").getFloat(null)==1);
  module("inputfix",true);data().getAsJsonObject("modules").getAsJsonObject("inputfix").addProperty("layout","FR AZERTY");apply();check("Input Foundation keyboard layout binding",p.getField("newKeybindHandling").getBoolean(null)&&p.getField("keyboardLayout").getInt(null)==2);
  module("inputfix",false);apply();check("Input Fix OFF resets key handling",!p.getField("newKeybindHandling").getBoolean(null)&&p.getField("keyboardLayout").getInt(null)==0);
  data().getAsJsonObject("modules").getAsJsonObject("inputfix").addProperty("layout","QWERTY");module("inputfix",true);apply();
  module("scrollfix",true);apply();check("scrollfix ON reaches official Patcher",p.getField("preventOverflowHotbarScrolling").getBoolean(null));module("scrollfix",false);apply();check("scrollfix OFF reaches official Patcher",!p.getField("preventOverflowHotbarScrolling").getBoolean(null));
  module("glint",true);apply();check("glint ON reaches official Patcher",p.getField("disableEnchantmentGlint").getBoolean(null));module("glint",false);apply();check("glint OFF reaches official Patcher",!p.getField("disableEnchantmentGlint").getBoolean(null));
  module("smoothscroll",true);apply();check("smoothscroll ON reaches official Patcher",p.getField("smoothScrolling").getBoolean(null));module("smoothscroll",false);apply();check("smoothscroll OFF reaches official Patcher",!p.getField("smoothScrolling").getBoolean(null));
  module("numericalenchants",true);apply();check("numericalenchants ON reaches official Patcher",p.getField("numericalEnchants").getBoolean(null));module("numericalenchants",false);apply();check("numericalenchants OFF reaches official Patcher",!p.getField("numericalEnchants").getBoolean(null));
  module("chatstamp",true);apply();check("chatstamp ON reaches official Patcher",p.getField("timestamps").getBoolean(null));module("chatstamp",false);apply();check("chatstamp OFF reaches official Patcher",!p.getField("timestamps").getBoolean(null));
  module("smartdisconnect",true);apply();check("smartdisconnect ON reaches official Patcher",p.getField("smartDisconnect").getBoolean(null));module("smartdisconnect",false);apply();check("smartdisconnect OFF reaches official Patcher",!p.getField("smartDisconnect").getBoolean(null));
  module("confirmquit",true);apply();check("confirmquit ON reaches official Patcher",p.getField("confirmQuit").getBoolean(null));module("confirmquit",false);apply();check("confirmquit OFF reaches official Patcher",!p.getField("confirmQuit").getBoolean(null));
  module("tablayers",true);apply();check("tablayers ON reaches official Patcher",p.getField("layersInTab").getBoolean(null));module("tablayers",false);apply();check("tablayers OFF reaches official Patcher",!p.getField("layersInTab").getBoolean(null));
  module("packimages",true);apply();check("packimages ON reaches official Patcher",p.getField("downscalePackImages").getBoolean(null));module("packimages",false);apply();check("packimages OFF reaches official Patcher",!p.getField("downscalePackImages").getBoolean(null));
  module("fontcache",true);apply();check("fontcache ON reaches official Patcher",p.getField("cacheFontData").getBoolean(null));module("fontcache",false);apply();check("fontcache OFF reaches official Patcher",!p.getField("cacheFontData").getBoolean(null));
  module("batchmodels",true);apply();check("batchmodels ON reaches official Patcher",p.getField("batchModelRendering").getBoolean(null));module("batchmodels",false);apply();check("batchmodels OFF reaches official Patcher",!p.getField("batchModelRendering").getBoolean(null));
  module("entrycache",true);apply();check("entrycache ON reaches official Patcher",p.getField("cacheEntrypoints").getBoolean(null));module("entrycache",false);apply();check("entrycache OFF reaches official Patcher",!p.getField("cacheEntrypoints").getBoolean(null));
  module("windowedfullscreen",true);apply();check("windowedfullscreen ON reaches official Patcher",p.getField("windowedFullscreen").getBoolean(null));module("windowedfullscreen",false);apply();check("windowedfullscreen OFF reaches official Patcher",!p.getField("windowedFullscreen").getBoolean(null));
 }
 void patcherWorld()throws Exception{
  if(!Boolean.getBoolean("ttro.qa.patcher"))return;Minecraft m=Minecraft.getMinecraft();float yaw=m.thePlayer.rotationYaw,head=m.thePlayer.rotationYawHead,pitch=m.thePlayer.rotationPitch;
  m.thePlayer.rotationYaw=0;m.thePlayer.rotationYawHead=90;m.thePlayer.rotationPitch=0;Vec3 look=m.thePlayer.getLook(1);
  check("Mouse Delay Foundation uses current local aim",Math.abs(look.xCoord)<.001&&look.zCoord>.999);
  m.thePlayer.rotationYaw=yaw;m.thePlayer.rotationYawHead=head;m.thePlayer.rotationPitch=pitch;
  module("fov",true);apply();net.minecraftforge.client.event.FOVUpdateEvent fov=new net.minecraftforge.client.event.FOVUpdateEvent(m.thePlayer,1.25f);net.minecraftforge.common.MinecraftForge.EVENT_BUS.post(fov);check("Static FOV real Forge event",Math.abs(fov.newfov-1)<.001);
  module("fov",false);apply();fov=new net.minecraftforge.client.event.FOVUpdateEvent(m.thePlayer,1.25f);net.minecraftforge.common.MinecraftForge.EVENT_BUS.post(fov);check("Static FOV OFF preserves vanilla event",Math.abs(fov.newfov-1.25f)<.001);
  module("waterfov",true);apply();net.minecraftforge.client.event.EntityViewRenderEvent.FOVModifier water=new net.minecraftforge.client.event.EntityViewRenderEvent.FOVModifier(m.entityRenderer,m.thePlayer,Blocks.water,0,60);net.minecraftforge.common.MinecraftForge.EVENT_BUS.post(water);check("Water FOV real rendering event",Math.abs(water.getFOV()-70)<.001);
  module("waterfov",false);apply();water=new net.minecraftforge.client.event.EntityViewRenderEvent.FOVModifier(m.entityRenderer,m.thePlayer,Blocks.water,0,60);net.minecraftforge.common.MinecraftForge.EVENT_BUS.post(water);check("Water FOV OFF preserves vanilla",Math.abs(water.getFOV()-60)<.001);
  module("nightvision",true);apply();m.thePlayer.addPotionEffect(new net.minecraft.potion.PotionEffect(net.minecraft.potion.Potion.nightVision.id,180));Method brightness=null;
  for(Method method:EntityRenderer.class.getDeclaredMethods())if((method.getName().equals("getNightVisionBrightness")||method.getName().equals("func_180438_a"))&&method.getParameterTypes().length==2){brightness=method;break;}
  if(brightness==null)throw new NoSuchMethodException("Minecraft night vision rendering");brightness.setAccessible(true);check("Night Vision cleanup actual transformed renderer",Math.abs(((Float)brightness.invoke(m.entityRenderer,m.thePlayer,0f))-.9f)<.001);module("nightvision",false);apply();m.thePlayer.removePotionEffect(net.minecraft.potion.Potion.nightVision.id);
 }
 EntityPlayerMP player(){Minecraft m=Minecraft.getMinecraft();return m.getIntegratedServer().getConfigurationManager().getPlayerByUUID(m.thePlayer.getUniqueID());}
 void inventory()throws Exception{Minecraft m=Minecraft.getMinecraft();m.displayGuiScreen(null);m.getIntegratedServer().addScheduledTask(()->{EntityPlayerMP p=player();p.inventory.clear();p.inventory.addItemStackToInventory(new ItemStack(Items.skull,8,3));p.inventoryContainer.detectAndSendChanges();});}
 void wheelSettings(int test)throws Exception{boolean first=test==5,reverse=test>=7;if(ttro){JsonObject inventory=data().getAsJsonObject("modules").getAsJsonObject("inventory");inventory.addProperty("searchDirection",first?"First to last":"Last to first");inventory.addProperty("scrollDirection",reverse?"Reverse":"Normal");apply();}else{Class<?> main=Class.forName("yalter.mousetweaks.Main");Object config=main.getField("config").get(null);Class<?> order=Class.forName("yalter.mousetweaks.WheelSearchOrder");config.getClass().getField("wheelSearchOrder").set(config,order.getMethod("fromId",int.class).invoke(null,first?0:1));}}
 void pointer(int x,int y){Minecraft m=Minecraft.getMinecraft();ScaledResolution r=new ScaledResolution(m);robot.mouseMove(org.lwjgl.opengl.Display.getX()+x*m.displayWidth/r.getScaledWidth(),org.lwjgl.opengl.Display.getY()+y*m.displayHeight/r.getScaledHeight());}
 void click(){robot.mousePress(InputEvent.BUTTON1_MASK);robot.mouseRelease(InputEvent.BUTTON1_MASK);}
 void chest(){Minecraft m=Minecraft.getMinecraft();m.getIntegratedServer().addScheduledTask(()->{EntityPlayerMP p=player();p.closeScreen();p.inventory.clear();p.inventory.setInventorySlotContents(9,new ItemStack(Items.stick,8));p.inventory.setInventorySlotContents(10,new ItemStack(Items.stick,8));InventoryBasic inv=new InventoryBasic("Ttro QA",false,9);inv.setInventorySlotContents(0,new ItemStack(Items.stick,8));inv.setInventorySlotContents(1,new ItemStack(Items.stick,8));p.displayGUIChest(inv);p.openContainer.detectAndSendChanges();});}
 void move(int slot)throws Exception{Minecraft m=Minecraft.getMinecraft();if(!(m.currentScreen instanceof GuiChest))throw new IllegalStateException("Chest not open");GuiChest g=(GuiChest)m.currentScreen;Slot s=g.inventorySlots.getSlot(slot);ScaledResolution r=new ScaledResolution(m);int left=(r.getScaledWidth()-176)/2,top=(r.getScaledHeight()-132)/2;robot.mouseMove(org.lwjgl.opengl.Display.getX()+(int)((left+s.xDisplayPosition+8)*(double)m.displayWidth/r.getScaledWidth()),org.lwjgl.opengl.Display.getY()+(int)((top+s.yDisplayPosition+8)*(double)m.displayHeight/r.getScaledHeight()));}
 void snapshot(String name){Minecraft m=Minecraft.getMinecraft();JsonArray slots=new JsonArray();for(Object slot:((GuiChest)m.currentScreen).inventorySlots.inventorySlots){ItemStack s=((Slot)slot).getStack();slots.add(new JsonPrimitive(s==null?0:s.stackSize));}JsonObject c=new JsonObject();c.addProperty("name",name);c.addProperty("status","CAPTURED");c.add("slots",slots);ItemStack held=m.thePlayer.inventory.getItemStack();c.addProperty("held",held==null?0:held.stackSize);checks.add(c);save();}
 @SubscribeEvent public void render(TickEvent.RenderTickEvent e){if(e.phase!=TickEvent.Phase.END)return;long now=System.nanoTime();if((stage==10||stage==11)&&elapsed>100&&last!=0&&frameCount<frameNanos.length){frameNanos[frameCount]=now-last;frameHeap[frameCount]=Runtime.getRuntime().totalMemory()-Runtime.getRuntime().freeMemory();frameModes[frameCount]=(byte)(stage==10?0:1);frameWindows[frameCount]=(short)benchmarkWindow;frameCount++;}last=now;}

 @SubscribeEvent public void tick(TickEvent.ClientTickEvent e){if(e.phase!=TickEvent.Phase.END)return;Minecraft m=Minecraft.getMinecraft();ticks++;elapsed++;
 try{
 if(stage==0&&m.currentScreen instanceof GuiMainMenu&&ticks>80){check("Forge and main menu",true);if(ttro){check("Ttro Client window title",org.lwjgl.opengl.Display.getTitle().startsWith("Ttro Client"));patcherSettings();offHud();check("Forge Mods config entry",Class.forName("dev.ttro.TtroGuiFactory").getMethod("mainConfigGuiClass").invoke(Class.forName("dev.ttro.TtroGuiFactory").newInstance())==Class.forName("dev.ttro.SettingsScreen"));KeyBinding settings=(KeyBinding)Class.forName("dev.ttro.Core").getField("settingsKey").get(null);check("Ttro shortcut avoids OneConfig default",settings.getKeyCode()==org.lwjgl.input.Keyboard.KEY_RCONTROL);}if(ttro){Class<?> modern=Class.forName("dev.ttro.ModernTab");check("Modern Tab normal data supported",(Boolean)modern.getMethod("supports",int.class,boolean.class,boolean.class).invoke(null,5,false,false));check("Modern Tab server metadata preserved by fallback",!(Boolean)modern.getMethod("supports",int.class,boolean.class,boolean.class).invoke(null,5,true,false)&&!(Boolean)modern.getMethod("supports",int.class,boolean.class,boolean.class).invoke(null,5,false,true));check("Modern Tab large list fallback",!(Boolean)modern.getMethod("supports",int.class,boolean.class,boolean.class).invoke(null,81,false,false));}shot("main-menu");m.gameSettings.pauseOnLostFocus=false;m.gameSettings.renderDistanceChunks=2;m.gameSettings.limitFramerate=Integer.getInteger("ttro.qa.fps",60);result.addProperty("fps_cap",m.gameSettings.limitFramerate);m.gameSettings.guiScale=2;m.gameSettings.enableVsync=false;if(ttro){module("scoreboard",true);apply();KeyBinding.onTick(((KeyBinding)Class.forName("dev.ttro.Core").getField("settingsKey").get(null)).getKeyCode());stage=1;}else stage=2;elapsed=0;}
 else if(stage==1&&elapsed>30){shot("native-settings");check("native Module settings rendered",m.currentScreen.getClass().getName().equals("dev.ttro.SettingsScreen"));if(Boolean.getBoolean("ttro.qa.fast")){previousCrosshair=data().getAsJsonObject("modules").getAsJsonObject("crosshair").get("enabled").getAsBoolean();robot.mouseMove(org.lwjgl.opengl.Display.getX()+500,org.lwjgl.opengl.Display.getY()+482);robot.mousePress(InputEvent.BUTTON1_MASK);robot.mouseRelease(InputEvent.BUTTON1_MASK);stage=18;}else stage=2;elapsed=0;}
 else if(stage==18&&elapsed>20){check("native context pointer navigation",m.currentScreen.getClass().getName().endsWith("ModuleScreen"));shot("native-context");robot.mouseMove(org.lwjgl.opengl.Display.getX()+100,org.lwjgl.opengl.Display.getY()+152);robot.mousePress(InputEvent.BUTTON1_MASK);robot.mouseRelease(InputEvent.BUTTON1_MASK);stage=19;elapsed=0;}
 else if(stage==19&&elapsed>20){check("native Module ON/OFF pointer",data().getAsJsonObject("modules").getAsJsonObject("crosshair").get("enabled").getAsBoolean()!=previousCrosshair);robot.keyPress(java.awt.event.KeyEvent.VK_ESCAPE);robot.keyRelease(java.awt.event.KeyEvent.VK_ESCAPE);stage=20;elapsed=0;}
 else if(stage==20&&elapsed>20){check("native Escape returns parent",m.currentScreen.getClass().getName().equals("dev.ttro.SettingsScreen"));module("hypixel",true);apply();Class<?> api=Class.forName("dev.ttro.HypixelBridge");Field initialized=api.getDeclaredField("initialized");initialized.setAccessible(true);check("official Mod API handlers registered offline",initialized.getBoolean(null));m.setServerData(new net.minecraft.client.multiplayer.ServerData("QA","mc.hypixel.net",false));Class<?> safety=Class.forName("dev.ttro.Safety");safety.getMethod("update").invoke(null);check("Hypixel fixture blocks inventory",!(Boolean)safety.getMethod("allowed",String.class).invoke(null,"inventory"));m.setServerData(null);safety.getMethod("update").invoke(null);check("safety clears after server change",(Boolean)safety.getMethod("allowed",String.class).invoke(null,"inventory"));data().getAsJsonObject("hud").addProperty("layout","clusters");apply();pointer(50,210);click();stage=21;elapsed=0;}
 else if(stage==21&&elapsed>20){check("native HUD editor navigation",m.currentScreen.getClass().getName().equals("dev.ttro.HudEditorScreen"));pointer(140,new ScaledResolution(m).getScaledHeight()-54);click();stage=22;elapsed=0;}
 else if(stage==22&&elapsed>20){check("native individual HUD mode",data().getAsJsonObject("hud").get("layout").getAsString().equals("individual"));pointer(20,19);robot.mousePress(InputEvent.BUTTON1_MASK);stage=23;elapsed=0;}
 else if(stage==23&&elapsed>10){pointer(120,80);stage=24;elapsed=0;}
 else if(stage==24&&elapsed>15){robot.mouseRelease(InputEvent.BUTTON1_MASK);JsonObject fps=data().getAsJsonObject("hud").getAsJsonObject("elements").getAsJsonObject("fps");check("native FPS HUD drag placement",fps.get("x").getAsFloat()>50&&fps.get("y").getAsFloat()>40);robot.keyPress(java.awt.event.KeyEvent.VK_TAB);robot.keyRelease(java.awt.event.KeyEvent.VK_TAB);robot.keyPress(java.awt.event.KeyEvent.VK_RIGHT);robot.keyRelease(java.awt.event.KeyEvent.VK_RIGHT);stage=25;elapsed=0;}
 else if(stage==25&&elapsed>15){check("native HUD Tab and arrow movement",data().getAsJsonObject("hud").getAsJsonObject("elements").getAsJsonObject("ping").get("x").getAsFloat()==13);shot("native-hud-editor");robot.keyPress(java.awt.event.KeyEvent.VK_ESCAPE);robot.keyRelease(java.awt.event.KeyEvent.VK_ESCAPE);stage=26;elapsed=0;}
 else if(stage==26&&elapsed>15){check("native HUD Escape returns parent",m.currentScreen.getClass().getName().equals("dev.ttro.SettingsScreen"));JsonObject persisted=new JsonParser().parse(new FileReader(new File(m.mcDataDir,"config/ttro-client.json"))).getAsJsonObject();check("native HUD positions persisted",persisted.getAsJsonObject("hud").getAsJsonObject("elements").getAsJsonObject("fps").get("x").getAsFloat()>50);stage=12;save();m.shutdown();}
 else if(stage==2&&elapsed>30){m.displayGuiScreen(null);m.launchIntegratedServer("TtroQA","Ttro QA",new WorldSettings(12345L,WorldSettings.GameType.CREATIVE,false,false,WorldType.FLAT));stage=3;elapsed=0;}
 else if(stage==3&&m.thePlayer!=null&&elapsed>100){check("local Forge world joined",true);if(Boolean.getBoolean("ttro.qa.packs")){try(InputStream texture=m.getResourceManager().getResource(new ResourceLocation("minecraft","textures/items/stick.png")).getInputStream()){java.awt.image.BufferedImage image=javax.imageio.ImageIO.read(texture);check("Launcher pack order consumed by real Minecraft",image.getRGB(0,0)==0xff2030dd);}check("two resource packs enabled in Minecraft",m.gameSettings.resourcePacks.size()==2);}if(Boolean.getBoolean("ttro.qa.patcher")){patcherWorld();inventoryKey=m.gameSettings.keyBindInventory.getKeyCode();m.gameSettings.keyBindInventory.setKeyCode(-99);KeyBinding.resetKeyBindingArrayAndHash();m.displayGuiScreen(new GuiInventory(m.thePlayer));stage=28;}else{inventory();stage=4;}elapsed=0;}
 else if(stage==28&&elapsed>15){pointer(20,45);robot.mousePress(InputEvent.BUTTON3_MASK);robot.mouseRelease(InputEvent.BUTTON3_MASK);stage=29;elapsed=0;}
 else if(stage==29&&elapsed>15){check("Mouse Bind Foundation closes inventory with RMB",m.currentScreen==null);m.gameSettings.keyBindInventory.setKeyCode(inventoryKey);KeyBinding.resetKeyBindingArrayAndHash();inventory();stage=4;elapsed=0;}
 else if(stage==4&&elapsed>40&&Boolean.getBoolean("ttro.qa.benchOnly")){if(ttro){for(JsonElement item:(JsonArray)Class.forName("dev.ttro.Config").getField("catalog").get(null)){JsonObject o=item.getAsJsonObject();if(!o.get("status").getAsString().equals("candidate"))module(o.get("id").getAsString(),false);}apply();}stage=10;elapsed=0;}
 else if(stage==4&&elapsed>40){shot("hud-headfx");if(ttro){module("headfx",false);apply();}stage=5;elapsed=0;}
 else if(stage==5&&elapsed>30){shot("headfx-off");if(ttro){module("headfx",true);data().getAsJsonObject("modules").getAsJsonObject("headfx").addProperty("preset","Glow");apply();}stage=15;elapsed=0;}
 else if(stage==15&&elapsed>20){shot("headfx-glow");if(ttro){data().getAsJsonObject("modules").getAsJsonObject("headfx").addProperty("threeD",true);apply();}stage=16;elapsed=0;}
 else if(stage==16&&elapsed>20){shot("headfx-3d");if(ttro){data().getAsJsonObject("modules").getAsJsonObject("headfx").addProperty("threeD",false);data().getAsJsonObject("modules").getAsJsonObject("headfx").addProperty("preset","Clean");apply();}stage=17;elapsed=0;}
 else if(stage==17&&elapsed>20){shot("headfx-clean");stage=6;elapsed=0;}
 else if(stage==6&&elapsed>20){if(ttro){net.minecraft.scoreboard.Scoreboard b=m.theWorld.getScoreboard();ScoreObjective obj=b.addScoreObjective("qa",IScoreObjectiveCriteria.DUMMY);obj.setDisplayName("UNKNOWN QA SERVER");b.setObjectiveInDisplaySlot(1,obj);b.getValueFromObjective("Unknown: preserve this line",obj).setScorePoints(1);}stage=7;elapsed=0;}
 else if(stage==7&&elapsed>30){shot("scoreboard-fallback");if(ttro){net.minecraft.scoreboard.Scoreboard b=m.theWorld.getScoreboard();ScoreObjective obj=b.getObjective("qa");b.removeObjective(obj);obj=b.addScoreObjective("qa2",IScoreObjectiveCriteria.DUMMY);obj.setDisplayName("BED WARS");b.setObjectiveInDisplaySlot(1,obj);String[] rows={"Diamond II in 4:32","R Red: ALIVE","B Blue: ALIVE","Kills: 3","Final Kills: 1"};for(int i=0;i<rows.length;i++)b.getValueFromObjective(rows[i],obj).setScorePoints(rows.length-i);Class<?> c=Class.forName("dev.ttro.Scoreboard");check("unknown scoreboard falls back",c.getMethod("parse",String.class,List.class).invoke(null,"OTHER",Arrays.asList("unknown"))==null);Object panel=c.getMethod("parse",String.class,List.class).invoke(null,"BED WARS",Arrays.asList(rows));check("strict Bed Wars parser",panel!=null);check("semantic scoreboard stats and timer",((Map)panel.getClass().getField("own").get(panel)).get("Finals").equals(1)&&panel.getClass().getField("timer").get(panel).equals("04:32"));check("unknown team state falls back",c.getMethod("parse",String.class,List.class).invoke(null,"BED WARS",Arrays.asList("R Red: UNKNOWN","B Blue: ALIVE","Kills: 3"))==null);}stage=8;elapsed=0;}
 else if(stage==8&&elapsed>30){shot("smart-scoreboard");if(ttro)Class.forName("dev.ttro.Core").getField("combatUntil").setLong(null,System.currentTimeMillis()+3000);stage=27;elapsed=0;}
 else if(stage==27&&elapsed>20){shot("scoreboard-combat");stage=9;elapsed=0;sub=0;chest();}
 else if(stage==9&&elapsed==20){wheelSettings(sub);move(0);if(sub==0){robot.mousePress(InputEvent.BUTTON1_MASK);robot.mouseRelease(InputEvent.BUTTON1_MASK);}else if(sub==1){robot.mousePress(InputEvent.BUTTON1_MASK);robot.mouseRelease(InputEvent.BUTTON1_MASK);}else if(sub==2){robot.keyPress(java.awt.event.KeyEvent.VK_SHIFT);robot.mousePress(InputEvent.BUTTON1_MASK);}else{int direction=sub==3||sub==7?1:-1;if(!ttro&&sub>=7)direction=-direction;robot.mouseWheel(direction);}}
 else if(stage==9&&elapsed==30){if(sub==0){move(2);robot.mousePress(InputEvent.BUTTON3_MASK);}else if(sub==1){move(1);robot.mousePress(InputEvent.BUTTON1_MASK);}else if(sub==2)move(1);}
 else if(stage==9&&elapsed==40){if(sub==0)move(3);else if(sub==1)move(9);}
 else if(stage==9&&elapsed==50){if(sub==0)move(2);}
 else if(stage==9&&elapsed==60){robot.mouseRelease(InputEvent.BUTTON3_MASK);robot.mouseRelease(InputEvent.BUTTON1_MASK);robot.keyRelease(java.awt.event.KeyEvent.VK_SHIFT);}
 else if(stage==9&&elapsed==75){snapshot(cases[sub]);shot(cases[sub]);sub++;if(sub<cases.length){chest();elapsed=0;}else{m.displayGuiScreen(null);if(Boolean.getBoolean("ttro.qa.inventoryOnly")){save();stage=12;m.shutdown();return;}if(ttro){for(JsonElement item:(JsonArray)Class.forName("dev.ttro.Config").getField("catalog").get(null)){JsonObject o=item.getAsJsonObject();if(!o.get("status").getAsString().equals("candidate"))module(o.get("id").getAsString(),false);}apply();}stage=10;elapsed=0;}}
 else if(stage==10&&elapsed>300){if(ttro){module("fps",true);module("cps",true);module("ping",true);module("crosshair",true);module("headfx",true);module("inventory",true);data().getAsJsonObject("modules").getAsJsonObject("headfx").addProperty("preset","Competitive");apply();}stage=11;benchmarkWindow++;elapsed=0;}
 else if(stage==11&&elapsed>300){if(benchmarkWindow<Integer.getInteger("ttro.qa.windows",1)){if(ttro){module("fps",false);module("cps",false);module("ping",false);module("crosshair",false);module("headfx",false);module("inventory",false);apply();}benchmarkWindow++;stage=10;elapsed=0;return;}check("render OFF/ON frame samples captured",frameCount>100);save();stage=12;m.shutdown();}
 }catch(Throwable ex){check("exception: "+ex.toString(),false);ex.printStackTrace();stage=12;m.shutdown();}
 }
}
