package dev.ttro;
import com.google.gson.JsonObject;
import java.io.IOException;
import net.minecraft.client.gui.*;
import org.lwjgl.input.Keyboard;

/** Local presentation editing only. Saves on release/back; no gameplay input automation. */
public final class HudEditorScreen extends GuiScreen {
 private final GuiScreen parent;private int selected;private boolean dragging;private float offsetX,offsetY;
 public HudEditorScreen(GuiScreen parent){this.parent=parent;}
 private boolean individual(){return Config.data.getAsJsonObject("hud").get("layout").getAsString().equals("individual");}
 private JsonObject position(){JsonObject h=Config.data.getAsJsonObject("hud");return individual()?h.getAsJsonObject("elements").getAsJsonObject(Hud.ELEMENT_IDS[selected]):h;}
 @Override public void initGui(){buttonList.clear();buttonList.add(new SettingsScreen.FlatButton(1,10,height-64,65,20,"Back"));buttonList.add(new SettingsScreen.FlatButton(2,85,height-64,110,20,individual()?"Individual":"Clusters"));buttonList.add(new SettingsScreen.FlatButton(3,205,height-64,70,20,"Reset"));Core.hud().refresh();}
 @Override public void drawScreen(int mouseX,int mouseY,float partial){drawRect(0,0,width,height,0x80212a35);if(dragging){JsonObject p=position();p.addProperty("x",Math.max(0,Math.min(width-16,mouseX-offsetX)));p.addProperty("y",Math.max(0,Math.min(height-16,mouseY-offsetY)));}Core.hud().drawLayout(new ScaledResolution(mc),true,selected);drawRect(0,height-70,width,height,0xe0212a35);super.drawScreen(mouseX,mouseY,partial);fontRendererObj.drawSplitString("Drag to move. Tab: select. Arrows: move. +/-: scale. Escape: save & back.",10,height-34,width-20,0xffffffff);fontRendererObj.drawString(individual()?Core.hud().elements[selected].label:"HUD Clusters",285,height-57,0xffffcc74);}
 @Override protected void mouseClicked(int x,int y,int button)throws IOException{super.mouseClicked(x,y,button);if(button!=0||y>=height-70)return;Hud hud=Core.hud();JsonObject settings=Config.data.getAsJsonObject("hud");if(individual()){boolean hit=false;for(int i=hud.elements.length-1;i>=0;i--){JsonObject p=settings.getAsJsonObject("elements").getAsJsonObject(Hud.ELEMENT_IDS[i]);float s=p.get("scale").getAsFloat(),w=hud.entryWidth(i)*s,h=(Math.max(1,hud.elements[i].count)*11+4)*s;float px=Math.max(0,Math.min(p.get("x").getAsFloat(),width-w)),py=Math.max(0,Math.min(p.get("y").getAsFloat(),height-h));if(x>=px&&x<=px+w&&y>=py&&y<=py+h){selected=i;offsetX=x-px;offsetY=y-py;hit=true;break;}}if(!hit)return;}else{offsetX=x-settings.get("x").getAsFloat();offsetY=y-settings.get("y").getAsFloat();}dragging=true;}
 @Override protected void mouseReleased(int x,int y,int state){if(dragging){dragging=false;Config.save();}super.mouseReleased(x,y,state);}
 @Override protected void actionPerformed(GuiButton button){if(button.id==1){Config.save();mc.displayGuiScreen(parent);}else if(button.id==2){Config.data.getAsJsonObject("hud").addProperty("layout",individual()?"clusters":"individual");Config.save();initGui();}else if(button.id==3){JsonObject p=position();p.addProperty("x",individual()?12+(selected/6)*220:12);p.addProperty("y",individual()?12+(selected%6)*26:12);p.addProperty("scale",1);Config.save();}}
 @Override protected void keyTyped(char c,int key)throws IOException{if(key==Keyboard.KEY_ESCAPE){Config.save();mc.displayGuiScreen(parent);return;}if(key==Keyboard.KEY_TAB){selected=(selected+(Keyboard.isKeyDown(Keyboard.KEY_LSHIFT)||Keyboard.isKeyDown(Keyboard.KEY_RSHIFT)?Hud.ELEMENT_IDS.length-1:1))%Hud.ELEMENT_IDS.length;return;}JsonObject p=position();int step=Keyboard.isKeyDown(Keyboard.KEY_LSHIFT)||Keyboard.isKeyDown(Keyboard.KEY_RSHIFT)?10:1;String axis=null;int delta=0;if(key==Keyboard.KEY_LEFT){axis="x";delta=-step;}if(key==Keyboard.KEY_RIGHT){axis="x";delta=step;}if(key==Keyboard.KEY_UP){axis="y";delta=-step;}if(key==Keyboard.KEY_DOWN){axis="y";delta=step;}if(axis!=null)p.addProperty(axis,Math.max(0,Math.min(axis.equals("x")?width-16:height-16,p.get(axis).getAsFloat()+delta)));if(c=='+'||c=='='||c=='-')p.addProperty("scale",Math.max(.5,Math.min(3,p.get("scale").getAsFloat()+(c=='-'?-.1:.1))));}
 @Override public boolean doesGuiPauseGame(){return false;}
}
