'use strict';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let state,view='play',group='PvP',selectedModule='crosshair',query='',saving=Promise.resolve(),lastFocus;
const profile=()=>state.profiles.find(x=>x.id===state.selected);
async function get(url){const r=await fetch(url);const d=await r.json();if(!r.ok)throw Error(d.error||'取得失敗');return d;}
async function action(action,b={}){const r=await fetch('/api/action',{method:'POST',headers:{'Content-Type':'application/json','X-Client-Token':state.token},body:JSON.stringify({action,profile:state.selected,...b})});const d=await r.json();if(!r.ok)throw Error(d.error||'保存失敗');return d;}
function notice(s){$('#notice span').textContent=s;$('#notice').hidden=false;}
async function guard(f){try{return await f();}catch(e){notice(e.message);return null;}}
async function refresh(render=true){state=await get('/api/state');document.documentElement.style.setProperty('--accent',state.product.accent);$('#profile-select').innerHTML=state.profiles.map(p=>`<option value="${p.id}" ${p.id===state.selected?'selected':''}>${esc(p.name)}</option>`).join('');if(render)draw();}
async function waitJob(id){for(;;){const j=await get('/api/job?id='+encodeURIComponent(id));if(j.status==='done')return j.result;if(j.status==='error')throw Error(j.error);await new Promise(r=>setTimeout(r,180));}}
function modal(title,html){lastFocus=document.activeElement;$('#modal-title').textContent=title;$('#modal-body').innerHTML=html;$('#modal').showModal();}
function scheduleSave(settings){const pid=state.selected;profile().settings=settings;$('#save-state').textContent='保存中…';saving=saving.catch(()=>{}).then(async()=>{const p=state.profiles.find(p=>p.id===pid);try{const result=await action('settings',{profile:pid,revision:p.revision,settings});p.revision=result.revision;$('#save-state').textContent='保存済';}catch(e){$('#save-state').textContent='保存失敗';notice(e.message);await refresh();throw e;}});saving.catch(()=>{});return saving;}
const styleGroup=m=>['HUD','Original','Visual','Clear View','Awareness'].includes(m.group);
function navigation(){const b=location.hash.slice(1).split('/');view=['play','tune','style','library'].includes(b[0])?b[0]:'play';if(view==='library')group=['mod','resourcepack','shader','profiles'].includes(b[1])?b[1]:'resourcepack';else if(b[1]&&state.modules.some(m=>m.id===b[1])){selectedModule=b[1];group=state.modules.find(m=>m.id===b[1]).group;}else group=view==='style'?'HUD':'PvP';query='';draw();}
function draw(){if(!state)return;$$('nav a').forEach(a=>a.setAttribute('aria-current',a.hash.split('/')[0]==='#'+view?'page':'false'));$('#main').innerHTML=view==='play'?play():view==='library'?library():modulesView();bind();}
function play(){const p=profile();return `<div class="eyebrow">PLAY / YOUR NEXT SESSION</div><h1>戦いの前に、ひとつ整える。</h1><div class="workspace"><section class="surface hero"><span class="chip">${esc(p.name)}</span><h2>いつものMinecraftを、<br>あなたの環境に。</h2><p class="note">Minecraft 1.8.9 • Forge 11.15.1.2318<br>機能・Pack・描画設定をこのProfileで管理します。</p><div class="actions"><button class="primary" data-act="launch">Minecraftを起動 ↗</button><button data-act="check">起動前チェック</button></div><p class="note">認証とゲーム配備はPrism Launcherへ引き継ぎます。</p></section><section class="surface"><h2>この環境の準備</h2><div class="footline">内蔵 ${state.modules.filter(m=>m.status==='implemented').length}機能 / 調査候補を含む ${state.modules.length}項目</div><div class="footline">外部Mod: ${p.content.filter(c=>c.kind==='mod').length}　Pack: ${p.content.filter(c=>c.kind==='resourcepack').length}</div>${p.integration?.message?`<p class="${p.integration.status==='review'?'error-box':'note'}">${esc(p.integration.message)}</p>`:''}<div class="actions"><button data-act="setup">外部基盤候補の導入内容を見る</button><button data-act="export">Profileを書き出す</button></div><details><summary>Prism Launcherの場所</summary><div class="setup-form"><label>実行ファイル<input id="prism-exe" value="${esc(state.prism)}"></label><label>データフォルダー<input id="prism-root" value="${esc(state.prismRoot||state.defaultPrismRoot)}"></label><button data-act="prism-save">場所を保存</button></div></details><p class="note">Alpha版です。候補項目を実装済みとして表示せず、ゲーム実機QAを継続しています。</p></section></div><section class="surface" style="margin-top:24px"><h2>軽さを選ぶ</h2><div class="tabs">${Object.keys(state.presets).map(n=>`<button data-preset="${n}" aria-pressed="${p.preset===n}">${n}</button>`).join('')}</div><p class="note">変更前に適用値を表示し、復元用Backupを作成します。測定なしにFPS向上を保証しません。</p></section>`;}
function modulesView(){const style=view==='style',groups=[...new Set(state.modules.filter(m=>style?styleGroup(m):!styleGroup(m)).map(m=>m.group))];if(!groups.includes(group))group=groups[0];return `<div class="eyebrow">${style?'STYLE / SEE WHAT MATTERS':'TUNE / CONTROL YOUR GAME'}</div><h1>${style?'見たい情報を、見たい場所へ。':'機能は並べる。設定は絞る。'}</h1><div class="tabs">${groups.map(g=>`<button data-group="${g}" aria-pressed="${group===g}">${g}</button>`).join('')}</div><label for="module-query">このカテゴリを検索</label><div class="filter"><input id="module-query" type="search" value="${esc(query)}" placeholder="機能名で絞り込む"></div><div class="module-layout"><section><div class="module-list" id="module-list">${moduleRows()}</div><p class="note">Input Foundationは修正基盤、Inventory Controlsは任意の操作機能として分離しています。</p></section><section class="surface context" id="context">${context()}</section></div>`;}
function moduleRows(){return state.modules.filter(m=>m.group===group&&m.name.toLowerCase().includes(query.toLowerCase())).map(m=>`<div class="module-row ${m.id===selectedModule?'selected':''}"><button data-module="${m.id}"><strong>${esc(m.name)}</strong><small>${esc(m.status==='implemented'?'内蔵':m.status==='external'?(profile().availability?.[m.id]===false?'外部Mod未導入・設定のみ':'外部Mod連携'):'候補・未実装')}</small></button>${m.control==='foundation'?`<span class="chip" data-foundation="${m.id}">${profile().availability?.[m.id]?'基盤有効':'未導入'}</span>`:`<input aria-label="${esc(m.name)}" type="checkbox" data-enable="${m.id}" ${profile().settings.modules[m.id].enabled?'checked':''} ${m.status==='candidate'||(profile().availability?.[m.id]===false&&!profile().settings.modules[m.id].enabled)?'disabled':''}>`}</div>`).join('')||'<div class="empty">該当する機能はありません。検索語を短くしてください。</div>';}
function context(){const m=state.modules.find(m=>m.id===selectedModule&&m.group===group)||state.modules.find(m=>m.group===group);selectedModule=m.id;const p=profile().settings.modules[m.id];return `<div class="eyebrow">${esc(m.group)}</div><h2>${esc(m.name)}</h2><span class="chip ${m.safety==='cosmetic'?'':'warn'}">Hypixel: ${m.safety==='cosmetic'?'規約の許容カテゴリに該当候補':m.safety==='restricted'?'制限対象':m.safety==='uncertain'?'要確認・安全側で制限':'要確認・許可を保証しません'}</span><p class="note">${esc(m.note)}</p><p class="note">提供: ${esc(m.provider)}</p>${m.control==='foundation'?'<p class="note">常設の入力修正です。導入状態を表示し、個別の切替は行いません。</p>':''}${profile().availability?.[m.id]===false?'<p class="error-box">提供Modが未導入です。LIBRARYから対応版を追加してください。</p>':''}${Object.entries(m.settings).map(([k,d])=>control(m,k,d,p[k])).join('')}${m.id==='headfx'?'<div class="preview"><div class="pixel-head">'+Array.from({length:16},()=>'<span></span>').join('')+'</div><span class="preview-caption">概念Preview • ゲームの描画結果ではありません</span></div>':''}${group==='HUD'?hudControls():''}<div class="footline">設定の既定キーは右Ctrl（Controlsで変更可）。Mods → Ttro Client → Configからも開けます。候補はONにできません。外部Modは導入状態と対応版の確認が必要です。</div>${m.id==='hypixel'?'<p class="note">Public APIレベル表示は未提供。APIキー入力・nick解除・毎frame通信は行いません。</p>':''}`;}
const labels={rightDrag:'Right-drag placement',leftCollect:'Left-drag collect',shiftDrag:'Shift-drag transfer',wheel:'Scroll transfer',scrollDirection:'Scroll direction',searchDirection:'Search direction',preset:'Preset',threeD:'Optional 3D',factor:'倍率',size:'サイズ',gap:'中央の隙間',shape:'形',target:'Vanilla対象で色変更',adaptive:'Adaptive表示',combatFocus:'Combatで補助情報を省く',party:'Party機能',showOwn:'自分にも表示',window:'分析サンプル数',height:'Fire height',opacity:'Fire opacity',layout:'Keyboard layout (Linux)' };
function control(m,k,d,v){const id=m.id+'-'+k;let f=d.type==='boolean'?`<input id="${id}" type="checkbox" ${v?'checked':''}>`:d.type==='select'?`<select id="${id}">${d.options.map(x=>`<option ${v===x?'selected':''}>${x}</option>`).join('')}</select>`:`<input id="${id}" type="number" min="${d.min}" max="${d.max}" step="${k==='factor'||k==='height'?.1:1}" value="${v}">`;return `<label class="control" for="${id}">${esc(labels[k]||k)} ${f.replace('id=',`data-param="${m.id}.${k}" data-type="${d.type}" id=`)}</label>`;}
function hudControls(){const s=profile().settings.hud,m=state.modules.find(m=>m.id===selectedModule),individual=s.elements?.[selectedModule];const fields=(p,element='')=>['x','y','scale'].map(k=>`<label class="control">${k==='scale'?'倍率':k.toUpperCase()}<input data-hud="${k}" ${element?`data-hud-element="${element}"`:''} type="number" min="${k==='scale'?.5:0}" max="${k==='scale'?3:10000}" step="${k==='scale'?.1:1}" value="${p[k]}"></label>`).join('');return `<details><summary>HUD配置と倍率</summary><label class="control">レイアウト<select data-hud="layout"><option value="clusters" ${s.layout==='clusters'?'selected':''}>Clusters</option><option value="individual" ${s.layout==='individual'?'selected':''}>Individual</option></select></label>${s.layout==='individual'&&individual?`<p>${esc(m.name)} の配置</p>${fields(individual,selectedModule)}`:fields(s)}<p class="note">座標はMinecraftのGUI単位。右Ctrl → HUD Editorで、ドラッグ・Tab・矢印キーでも編集できます。</p></details>`;}

function library(){const p=profile();return `<div class="eyebrow">LIBRARY / YOUR COLLECTION</div><h1>追加も、切替も、この場所で。</h1><div class="tabs">${[['resourcepack','Resource Packs'],['mod','Mods'],['shader','Shaders'],['profiles','Profiles']].map(([k,v])=>`<a href="#library/${k}" class="chip">${v}</a>`).join('')}</div>${group==='profiles'?`<section class="surface"><h2>Profiles</h2>${state.profiles.map(p=>`<div class="content-row"><strong class="grow">${esc(p.name)}</strong><button data-select="${p.id}">選択</button><button data-copy="${p.id}">複製</button></div>`).join('')}<div class="actions"><button data-act="backup">Backup</button><button data-act="restore">復元</button></div></section>`:`<div class="workspace"><section class="surface"><h2>導入済み</h2><label for="content-file">${group==='mod'?'Forge 1.8.9のJAR':'1.8.9のZIP'}を追加（64MiBまで）</label><input id="content-file" type="file" accept="${group==='mod'?'.jar':'.zip'}"><div id="content-list">${p.content.filter(c=>c.kind===group).map(c=>`<div class="content-row"><div class="grow"><strong>${esc(c.name)}</strong><div class="note">${esc(c.version)} · ${c.enabled?'有効':'無効'}</div></div><div class="actions"><button data-content="${esc(c.filename)}" data-op="${c.enabled?'disable':'enable'}">${c.enabled?'無効にする':'有効にする'}</button>${group==='resourcepack'?`<button data-preview="${esc(c.filename)}">Preview</button><button data-content="${esc(c.filename)}" data-op="up" aria-label="${esc(c.name)}の優先順位を上げる">↑</button><button data-content="${esc(c.filename)}" data-op="down" aria-label="${esc(c.name)}の優先順位を下げる">↓</button>`:''}</div></div>`).join('')||'<p class="empty">このProfileにはまだ追加されていません。</p>'}</div><button data-act="updates">更新を確認</button><p class="note">Resource Packは上ほど優先。Pack変更は次回起動に適用。Shaderには別途OptiFine等が必要です。OptiFineは配布許可がないため同梱していません。</p></section><section class="surface"><h2>探して追加</h2><form id="browse-form"><label for="browse-query">Modrinthを検索</label><div class="filter"><input id="browse-query" type="search" placeholder="例: PvP、16x、default"><button type="submit">検索</button></div></form><div id="browse-results" aria-live="polite"><p class="note">Minecraft 1.8.9対応の配布物を検索します。</p></div></section></div>`}`;}
function bind(){
 $$('[data-act]').forEach(b=>b.onclick=()=>guard(()=>runAct(b.dataset.act)));
 $$('[data-preset]').forEach(b=>b.onclick=()=>{modal('描画設定を適用',`<p>${esc(b.dataset.preset)}をこのProfileへ適用します。</p><div class="tablewrap"><table>${Object.entries(state.presets[b.dataset.preset]).map(([k,v])=>`<tr><td>${k}</td><td>${v}</td></tr>`).join('')}</table></div><button id="confirm-preset" class="primary">この変更を適用</button>`);$('#confirm-preset').onclick=()=>guard(async()=>{await action('preset',{name:b.dataset.preset});$('#modal').close();await refresh();});});
 $$('[data-group]').forEach(b=>b.onclick=()=>{group=b.dataset.group;query='';draw();});
 $$('[data-module]').forEach(b=>b.onclick=()=>{selectedModule=b.dataset.module;$('#context').innerHTML=context();$('#module-list').innerHTML=moduleRows();bind();});
 if($('#module-query'))$('#module-query').oninput=e=>{query=e.target.value;$('#module-list').innerHTML=moduleRows();bind();};
 $$('[data-enable]').forEach(e=>e.onchange=()=>{const s=structuredClone(profile().settings);s.modules[e.dataset.enable].enabled=e.checked;scheduleSave(s);});
 $$('[data-param]').forEach(e=>e.onchange=()=>{const [m,k]=e.dataset.param.split('.'),s=structuredClone(profile().settings);s.modules[m][k]=e.dataset.type==='boolean'?e.checked:e.dataset.type==='number'?Number(e.value):e.value;scheduleSave(s);});
 $$('[data-hud]').forEach(e=>e.onchange=()=>{const s=structuredClone(profile().settings);const target=e.dataset.hudElement?s.hud.elements[e.dataset.hudElement]:s.hud;target[e.dataset.hud]=e.dataset.hud==='layout'?e.value:Number(e.value);scheduleSave(s);if(e.dataset.hud==='layout'){$('#context').innerHTML=context();bind();$('#context details').open=true;$('#context [data-hud=layout]').focus();}});
 $$('[data-content]').forEach(b=>b.onclick=()=>guard(async()=>{await action('content',{filename:b.dataset.content,operation:b.dataset.op});await refresh();}));
 $$('[data-preview]').forEach(b=>b.onclick=()=>guard(async()=>{const r=await get('/api/pack-preview?profile='+state.selected+'&filename='+encodeURIComponent(b.dataset.preview));modal('Resource Pack Preview',`<p>${esc(r.notice)}</p>${r.images.map(x=>`<img alt="${esc(x.name)}" src="${x.data}" width="96" height="96" style="image-rendering:pixelated">`).join('')||'<p>対象画像がありません。</p>'}`);}));
 $$('[data-select]').forEach(b=>b.onclick=()=>guard(async()=>{await saving;await action('select',{profile:b.dataset.select});await refresh();}));
 $$('[data-copy]').forEach(b=>b.onclick=()=>guard(async()=>{await saving;await action('create',{source:b.dataset.copy,name:state.profiles.find(p=>p.id===b.dataset.copy).name+' (copy)'});await refresh();}));
 if($('#content-file'))$('#content-file').onchange=e=>guard(async()=>{const f=e.target.files[0];if(!f)return;if(f.size>64*1024*1024)throw Error('64MiB以下のファイルを選んでください。');const b=new Uint8Array(await f.arrayBuffer());let s='';for(let i=0;i<b.length;i+=16384)s+=String.fromCharCode(...b.subarray(i,i+16384));await action('importContent',{filename:f.name,kind:group,data:btoa(s)});await refresh();notice('追加しました。');});
 if($('#browse-form'))$('#browse-form').onsubmit=e=>{e.preventDefault();guard(browse);};
}
async function browse(){const t=$('#browse-results');t.innerHTML='<p role="status">検索中…</p>';try{const r=await get('/api/search?kind='+group+'&q='+encodeURIComponent($('#browse-query').value));t.innerHTML=r.hits.map(h=>`<div class="content-row"><div class="grow"><strong>${esc(h.title)}</strong><p class="note">${esc(h.description)}</p></div><button data-plan="${h.project_id}">導入内容を見る</button></div>`).join('')||'<p class="empty">該当する1.8.9版はありません。</p>';$$('[data-plan]').forEach(b=>b.onclick=()=>guard(async()=>{b.disabled=true;try{const j=await action('plan',{project:b.dataset.plan,kind:group});planModal(await waitJob(j.job));}finally{b.disabled=false;}}));}catch(e){t.innerHTML='<div class="error-box">'+esc(e.message)+' 再度「検索」で再試行できます。</div>';}}
function planModal(r){modal('導入内容を確認',`<p>${esc(r.notice)}</p>${r.nodes.map(n=>`<div class="content-row"><div class="grow"><strong>${esc(n.name)}</strong><p>${esc(n.previous_version||'未導入')} → ${esc(n.version)} · ${esc(n.change)}<br>License: ${esc(n.license.id)}</p>${n.license.url?`<a href="${esc(n.license.url)}" target="_blank" rel="noopener">Licenseを読む ↗</a>`:''}</div></div>`).join('')}<button id="install-plan" class="primary">この内容を導入</button>`);$('#install-plan').onclick=()=>guard(async()=>{const b=$('#install-plan');b.disabled=true;b.textContent='導入中…';try{const j=await action('install',{plan:r.plan});await waitJob(j.job);$('#modal').close();await refresh();notice('導入しました。');}catch(e){b.disabled=false;b.textContent='再試行';throw e;}});}
async function runAct(a){if(a==='launch'){const r=await action('launch');notice(r.message);}if(a==='prism-save'){await action('prism',{exe:$('#prism-exe').value,root:$('#prism-root').value});notice('場所を保存しました。');await refresh();}if(a==='check'){const r=await get('/api/check?profile='+state.selected);modal('起動前チェック',r.map(x=>`<p class="${x.level==='error'?'error-box':'note'}">${esc(x.message)}</p>`).join('')||'<p>metadata検査で明確な問題は検出されませんでした。実起動・互換性の保証ではありません。</p>');}if(a==='setup'){const j=await action('recommended-plan');planModal(await waitJob(j.job));}if(a==='export')location.href='/api/export?profile='+state.selected;if(a==='backup'){await action('backup');notice('Backupを作成しました。');}if(a==='restore'){const r=await get('/api/backups?profile='+state.selected);modal('このProfileを復元',r.length?`<label for="backup-select">Backup</label><select id="backup-select">${r.map(v=>`<option>${v}</option>`).join('')}</select><p>現在の設定もBackupしてから復元します。</p><button id="restore-confirm">復元する</button>`:'<p>Backupがまだありません。</p>');if(r.length)$('#restore-confirm').onclick=()=>guard(async()=>{await action('restore',{backup:$('#backup-select').value});$('#modal').close();await refresh();});}if(a==='updates'){const j=await action('updates');const r=await waitJob(j.job);modal('更新候補',r.map(x=>`<p>${esc(x.name)}: ${esc(x.from||'')} → ${esc(x.to||x.message||'')}</p>${x.plan?`<button data-update="${x.plan.plan}">変更内容</button>`:''}`).join('')||'<p>更新候補はありません。</p>');$$('[data-update]').forEach(b=>b.onclick=()=>planModal(r.find(x=>x.plan?.plan===b.dataset.update).plan));}}
$('#notice-close').onclick=()=>$('#notice').hidden=true;$$('[data-close]').forEach(b=>b.onclick=()=>b.closest('dialog').close());$$('dialog').forEach(d=>d.addEventListener('close',()=>{if(lastFocus?.isConnected)lastFocus.focus();else $('#main').focus();}));
$('#profile-select').onchange=e=>guard(async()=>{const pid=e.target.value;await saving;await action('select',{profile:pid});await refresh();});
$('#new-profile').onclick=()=>{modal('新しいProfile',`<label for="profile-name">名前（1〜80文字）</label><input id="profile-name" maxlength="80" value="Competitive"><button id="profile-create" class="primary">作成</button>`);$('#profile-create').onclick=()=>guard(async()=>{await saving;await action('create',{name:$('#profile-name').value});$('#modal').close();await refresh();});};
function commands(){const q=$('#command-query').value.toLowerCase(),aliases={headfx:'頭 ヘッド',inventory:'マウス スクロール インベントリ',fps:'軽さ フレーム',scoreboard:'スコアボード'};$('#command-results').innerHTML=state.modules.filter(m=>(m.name+' '+m.group+' '+(aliases[m.id]||'')).toLowerCase().includes(q)).map(m=>`<button data-command="${styleGroup(m)?'style':'tune'}/${m.id}">${esc(m.name)} <span class="note">${esc(m.group)}</span></button>`).join('')||'<p class="empty">該当する機能はありません。</p>';$$('[data-command]').forEach(b=>b.onclick=()=>{$('#palette').close();location.hash=b.dataset.command;});}
function openPalette(){if(!state)return;lastFocus=document.activeElement;$('#palette').showModal();$('#command-query').value='';commands();$('#command-query').focus();}
$('#search-open').onclick=openPalette;$('#command-query').oninput=commands;$('#command-query').onkeydown=e=>{if(e.key==='Enter'){$('[data-command]')?.click();e.preventDefault();}};document.addEventListener('keydown',e=>{if(e.key==='Escape'){const d=$('#modal').open?$('#modal'):$('#palette').open?$('#palette'):null;if(d){e.preventDefault();d.close();}}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();if(!$('#modal').open&&!$('#palette').open)openPalette();}});window.addEventListener('hashchange',()=>guard(async()=>{await saving;navigation();}));refresh(false).then(navigation).catch(e=>{$('#main').innerHTML='<div class="error-box">環境を読み込めませんでした。'+esc(e.message)+' ページを再読み込みしてください。</div>';});
